tap "daipeihust/tap", trusted: true
tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae", trusted: true
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "laishulu/homebrew", trusted: true
tap "localsend/localsend", trusted: true
tap "nikitabobko/tap", trusted: true
# Plugin manager for zsh, inspired by antigen and antibody
brew "antidote"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Package acting as bridge between Node projects and their package managers
brew "corepack"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Fast and simple Node.js version manager
brew "fnm"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Fast Cross-Platform Package Manager
brew "micromamba"
# Another rule-based tunnel in Go, formerly known as ClashMeta
brew "mihomo"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# Rsync for cloud storage
brew "rclone"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# macOS Input Source Manager
brew "laishulu/homebrew/macism"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# Android SDK component
cask "android-platform-tools"
# Virtual Audio Driver
cask "blackhole-2ch"
# Tool to list all active shortcuts of the current application
cask "cheatsheet"
# Automated testing of webapps for Google Chrome
cask "chromedriver"
# English dictionary
cask "eudic"
# Web browser
cask "firefox"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
# Desktop client for GitHub repositories
cask "github"
# Web browser
cask "google-chrome"
# Desktop automation application
cask "hammerspoon"
# Utility to hide menu bar items
cask "hiddenbar"
# Menu bar calendar
cask "itsycal"
# Open-source cross-platform alternative to AirDrop
cask "localsend"
# File system integration
cask "macfuse"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# IDE for professional Python development
cask "pycharm"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Instant messaging tool
cask "qq"
# Screenshot measurement and annotation tool
cask "shottr"
# Customizable email client
cask "thunderbird"
# Open-source code editor
cask "visual-studio-code"
# JavaScript IDE
cask "webstorm"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm@nightly"
vscode "af4jm.vscode-m3u"
vscode "ahmadalli.vscode-nginx-conf"
vscode "alanmbarr.quotify"
vscode "alefragnani.project-manager"
vscode "aykutsarac.jsoncrack-vscode"
vscode "catppuccin.catppuccin-vsc"
vscode "christian-kohler.path-intellisense"
vscode "deerawan.vscode-faker"
vscode "devzstudio.emoji-snippets"
vscode "dnicolson.binary-plist"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "github.codespaces"
vscode "github.vscode-github-actions"
vscode "grapecity.gc-excelviewer"
vscode "humao.rest-client"
vscode "janisdd.vscode-edit-csv"
vscode "jock.svg"
vscode "johnpapa.vscode-peacock"
vscode "kamikillerto.vscode-colorize"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.remote-explorer"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "rooveterinaryinc.roo-cline"
vscode "royaction.color-manager"
vscode "sirtori.indenticator"
vscode "streetsidesoftware.code-spell-checker"
vscode "sumneko.lua"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "unifiedjs.vscode-mdx"
vscode "usernamehw.indent-one-space"
vscode "viablelab.bracket-padder"
vscode "vscodevim.vim"
go "golang.org/x/tools/gopls"
npm "@bitwarden/cli"
